### ISSUE TITLE
Problem in set region

### ISSUE THREAD

**Issue by alizowghi** [satrobit/rancher-ui-driver-arvan#2]
Hi
I think there is a problem
pls see attached file
![Screenshot from 2020-06-30 18-26-30](https://user-images.githubusercontent.com/7982318/86134830-52650380-baff-11ea-9421-6d4711fb255f.png)

**Comment by satrobit** [comment]
You should probably report this issue to ArvanCloud since It's a 500 error from their API. Have you tried other locations like NL?

**Comment by alizowghi** [comment]
Thank you amir
you're right
They do not have the capacity in Iran, but they do in the Netherlands

**Comment by satrobit** [comment]
Glad I could help.
I consider this issue closed.
